FROM python:3

# Instalando as dependências do Robot Framework
RUN pip install --upgrade robotframework \
    robotframework-browser \
    robotframework-seleniumlibrary \
    robotframework-requests